version: '3.8'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758-serving
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}

