name: proyecto-data-science
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - opencv
  - tqdm
  - lxml
  - plotly
  - setuptools
  - ipykernel
  - ipywidgets
  - jupyterlab>=3.0.0
  - ipdb
  - scipy
  - pip
  - pip:
      - wandb
      - xgboost>=1.7.6